# Generated by Django 5.0.2 on 2024-03-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_direccion_envio_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
